# Generated by Django 5.0 on 2026-08-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('DONATION', '100% Free NGO Donation'), ('DISCOUNT', 'Discounted Consumer Sale')], default='DISCOUNT', max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('estimated_fmv', models.DecimalField(decimal_places=2, help_text='Fair Market Value for Tax Receipt', max_digits=6)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_start', models.DateTimeField()),
                ('pickup_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
