# Generated by Django 5.0 on 2026-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='quantity_unit',
            field=models.CharField(default='portions', max_length=20),
        ),
    ]
