# Generated by Django 5.0 on 2026-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_foodlisting_additional_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='dietary_info',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
