# Generated by Django 5.0 on 2026-08-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_foodlisting_dietary_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='ai_suggested_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='is_ai_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
