# Generated by Django 5.0 on 2026-08-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_foodlisting_ai_suggested_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='ai_suggested_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='estimated_fmv',
            field=models.DecimalField(decimal_places=2, help_text='Fair Market Value for Tax Receipt', max_digits=8),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
