# Generated by Django 5.0 on 2026-08-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_foodlisting_ai_suggested_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='ai_valuation_report',
            field=models.JSONField(blank=True, help_text='Detailed AI valuation breakdown', null=True),
        ),
    ]
