# Generated by Django 5.0 on 2026-08-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_foodlisting_ai_valuation_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='surplus_images/'),
        ),
    ]
