# Generated by Django 5.0 on 2026-08-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_business_name_user_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Kitchen/Donor'), ('shelter', 'Shelter/NGO'), ('consumer', 'Consumer'), ('admin', 'Admin')], default='consumer', max_length=20),
        ),
    ]
