# Generated by Django 5.0 on 2026-08-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BANNED', 'Banned')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_count',
            field=models.IntegerField(default=0),
        ),
    ]
