# Generated by Django 5.0 on 2026-08-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_rejection_reason'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
