# Generated by Django 5.0 on 2026-08-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('user', 'User Registration'), ('donation', 'New Donation'), ('rejection', 'User Rejection'), ('approval', 'User Approval'), ('rerequest', 'Re-request Approval'), ('ban', 'User Banned')], max_length=50),
        ),
    ]
