# Generated by Django 5.0 on 2026-08-12 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
