# Generated by Django 5.0 on 2026-08-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreceipt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
    ]
